version: '3.9'
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3002:3000'
    volumes:
      - ./:/app
      - ignore:/usr/local/apps/myapp/dev/node_modules/
volumes:
  ignore:
